name: Windows Build

on:
  workflow_call:

jobs:
  win-build:
    runs-on: self-hosted
    
    strategy:
      fail-fast: false
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        repository: novusengine/Game

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive

    - name: Run Premake
      run: |
        premake5 vs2022

    - name: Build
      run: |
        msbuild /m /p:Configuration=Debug Build/Game.sln

    - name: Upload Game App artifact
      uses: actions/upload-artifact@v4
      with:
        name: Game-App
        path: |
          Build/Bin/Game/Debug/Game-App.exe
          Build/Bin/Game/Debug/dxcompiler.dll
